// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ProtocBuff/GRPCClientTemplate.proto

package tt_git

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendData) Reset() {
	*x = SendData{}
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendData) ProtoMessage() {}

func (x *SendData) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendData.ProtoReflect.Descriptor instead.
func (*SendData) Descriptor() ([]byte, []int) {
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP(), []int{1}
}

func (x *SendData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type DataReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataReceipt) Reset() {
	*x = DataReceipt{}
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReceipt) ProtoMessage() {}

func (x *DataReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReceipt.ProtoReflect.Descriptor instead.
func (*DataReceipt) Descriptor() ([]byte, []int) {
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP(), []int{2}
}

func (x *DataReceipt) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DataStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataID        string                 `protobuf:"bytes,1,opt,name=DataID,proto3" json:"DataID,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataStatus) Reset() {
	*x = DataStatus{}
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStatus) ProtoMessage() {}

func (x *DataStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStatus.ProtoReflect.Descriptor instead.
func (*DataStatus) Descriptor() ([]byte, []int) {
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP(), []int{3}
}

func (x *DataStatus) GetDataID() string {
	if x != nil {
		return x.DataID
	}
	return ""
}

func (x *DataStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocBuff_GRPCClientTemplate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_ProtocBuff_GRPCClientTemplate_proto protoreflect.FileDescriptor

const file_ProtocBuff_GRPCClientTemplate_proto_rawDesc = "" +
	"\n" +
	"#ProtocBuff/GRPCClientTemplate.proto\x12\n" +
	"TestServer\".\n" +
	"\x04Data\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.TestServer.ItemR\x05items\"2\n" +
	"\bSendData\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.TestServer.ItemR\x05items\"\x1d\n" +
	"\vDataReceipt\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"<\n" +
	"\n" +
	"DataStatus\x12\x16\n" +
	"\x06DataID\x18\x01 \x01(\tR\x06DataID\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\"*\n" +
	"\x04Item\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xcb\x01\n" +
	"\x0fTestGRPCService\x128\n" +
	"\aGetData\x12\x17.TestServer.DataReceipt\x1a\x10.TestServer.Data\"\x000\x01\x12:\n" +
	"\aAddData\x12\x14.TestServer.SendData\x1a\x17.TestServer.DataReceipt\"\x00\x12B\n" +
	"\rGetDataStatus\x12\x17.TestServer.DataReceipt\x1a\x16.TestServer.DataStatus\"\x00B Z\x1egithub.com/FACELESS-GOD/tt.gitb\x06proto3"

var (
	file_ProtocBuff_GRPCClientTemplate_proto_rawDescOnce sync.Once
	file_ProtocBuff_GRPCClientTemplate_proto_rawDescData []byte
)

func file_ProtocBuff_GRPCClientTemplate_proto_rawDescGZIP() []byte {
	file_ProtocBuff_GRPCClientTemplate_proto_rawDescOnce.Do(func() {
		file_ProtocBuff_GRPCClientTemplate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ProtocBuff_GRPCClientTemplate_proto_rawDesc), len(file_ProtocBuff_GRPCClientTemplate_proto_rawDesc)))
	})
	return file_ProtocBuff_GRPCClientTemplate_proto_rawDescData
}

var file_ProtocBuff_GRPCClientTemplate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ProtocBuff_GRPCClientTemplate_proto_goTypes = []any{
	(*Data)(nil),        // 0: TestServer.Data
	(*SendData)(nil),    // 1: TestServer.SendData
	(*DataReceipt)(nil), // 2: TestServer.DataReceipt
	(*DataStatus)(nil),  // 3: TestServer.DataStatus
	(*Item)(nil),        // 4: TestServer.Item
}
var file_ProtocBuff_GRPCClientTemplate_proto_depIdxs = []int32{
	4, // 0: TestServer.Data.items:type_name -> TestServer.Item
	4, // 1: TestServer.SendData.items:type_name -> TestServer.Item
	2, // 2: TestServer.TestGRPCService.GetData:input_type -> TestServer.DataReceipt
	1, // 3: TestServer.TestGRPCService.AddData:input_type -> TestServer.SendData
	2, // 4: TestServer.TestGRPCService.GetDataStatus:input_type -> TestServer.DataReceipt
	0, // 5: TestServer.TestGRPCService.GetData:output_type -> TestServer.Data
	2, // 6: TestServer.TestGRPCService.AddData:output_type -> TestServer.DataReceipt
	3, // 7: TestServer.TestGRPCService.GetDataStatus:output_type -> TestServer.DataStatus
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ProtocBuff_GRPCClientTemplate_proto_init() }
func file_ProtocBuff_GRPCClientTemplate_proto_init() {
	if File_ProtocBuff_GRPCClientTemplate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ProtocBuff_GRPCClientTemplate_proto_rawDesc), len(file_ProtocBuff_GRPCClientTemplate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ProtocBuff_GRPCClientTemplate_proto_goTypes,
		DependencyIndexes: file_ProtocBuff_GRPCClientTemplate_proto_depIdxs,
		MessageInfos:      file_ProtocBuff_GRPCClientTemplate_proto_msgTypes,
	}.Build()
	File_ProtocBuff_GRPCClientTemplate_proto = out.File
	file_ProtocBuff_GRPCClientTemplate_proto_goTypes = nil
	file_ProtocBuff_GRPCClientTemplate_proto_depIdxs = nil
}
